### ISSUE TITLE
Using only settings.yml

### ISSUE THREAD

**Issue by JanC** [railsconfig/config#123] opened 2015-12-15 07:38 UTC
Hi,
is it possible to use only the `settings.yml` and have development and production sections instead if using two different `config/development/settings.yml` and `config/production/settings.yml` ?

```ruby
development:
  token_url: "http://localhost:3000"
production:
  token_url: "http://mysite.com"
```
Then access it via `Settings.token_url` ?

**Comment by hakimovis** [comment] 2015-12-15 07:45
```ruby
    def env_config
      Settings.send(Rails.env)
    end
```

**Comment by vinceve** [comment] 2016-01-14 11:19
@JanC What would be a use case for this behaviour, maybe there is another way to achieve the same thing? (just curious, I don't want to be harsh :-) )

**Comment by pkuczynski** [comment] 2016-05-12 13:03
This is against the "split config into separate env-based files" idea which was the merit for this gem. You should store all common and default bitty settings in config/settings.yml file and override only some of them when needed for a particular env.

This issue is also a duplicate of #105

**Closed by pkuczynski** 2016-05-12 13:03 UTC
