### ISSUE TITLE
Do not evaluate ERB in  YAML comments

### ISSUE THREAD

**Issue by skamansam** [railsconfig/config#109] opened 2015-06-25 21:05 UTC
Every time I try to configure RailsConfig, I get the following error:
```NameError: uninitialized constant AppConfig
```

I am trying to use the following code, in `config/environments/development.rb`:

```ruby
  config.action_mailer.default_url_options = {
    host: Settings.action_mailer.default_url_options.host,
    port: Settings.action_mailer.default_url_options.port
  }
```

and my config file is at `config/application/default.yml`:
```yaml
default:
  action_mailer:
    default_url_options:
      host: localhost
      port: 3000
```
It errors out when I try to load a yaml file, as in the following code. I have tried moving this code to config/application.rb, config/environments/development,  
```ruby
Settings.reload_from_files(
  File.join(Rails.root.to_s, "config", 'application', "default.yml").to_s,
  File.join(Rails.root.to_s, "config", 'application', "config.yml").to_s
)
```

Here is a sample stacktrace, when the code is in config/environment.rb:
```
(erb):17:in `<main>': uninitialized constant AppConfig (NameError)
        from /home/sam/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `eval'
        from /home/sam/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/erb.rb:863:in `result'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/rails_config-0.4.2/lib/rails_config/sources/yaml_source.rb:17:in `load'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/rails_config-0.4.2/lib/rails_config/options.rb:40:in `block in reload!'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/rails_config-0.4.2/lib/rails_config/options.rb:39:in `each'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/rails_config-0.4.2/lib/rails_config/options.rb:39:in `reload!'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/rails_config-0.4.2/lib/rails_config.rb:32:in `load_files'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/rails_config-0.4.2/lib/rails_config.rb:40:in `load_and_set_settings'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/rails_config-0.4.2/lib/rails_config/options.rb:60:in `reload_from_files'
        from /home/sam/workspace/my_app/config/environment.rb:3:in `<top (required)>'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:92:in `preload'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
        from /home/sam/.rvm/gems/ruby-2.2.2/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /home/sam/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/sam/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'

```
I am using Ruby 2.2.0, Rails 4.2.1, rails_config 0.4.2

**Comment by skamansam** [comment] 2015-06-25 21:11
This also happens in 0.5.0.beta1

**Comment by skamansam** [comment] 2015-06-25 21:17
I managed to figure out the problem: the issue is that the ERB from the comments in my YAML file were being evaluated

**Comment by fredwu** [comment] 2015-08-06 04:10
Hmmm, where does `AppConfig` come from? I don't think we have any reference to that in the code base. Could you elaborate the bit about the evaluation of ERB in YAML comments?

**Comment by pkuczynski** [comment] 2015-08-17 10:41
Or better attach your full settings file, so we can fix the problem and add some more specific examples to our test suite...

**Comment by pkuczynski** [comment] 2016-05-12 12:46
I am closing this one due lack of the feedback from reporter and low probability of this issue caused by config gem.

**Closed by pkuczynski** 2016-05-12 12:46 UTC
Labels: needs feedback
